version: 2

builds:
  - env:
    - CGO_ENABLED=0
    main: ./cmd/ops
    binary: ops
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
 
archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

changelog:
  sort: asc
  filters:
      include:
        - "^add:"
        - "^fix:"
        - "^change:"
