# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - version.txt
    - branch.txt
    - nuv
    - ops
    - env
    - go.mod
    - go.sum
    - '**/*.help'
    - 'attic/**'
    - 'bin/**'
    - 'tools/*/**'
    - '**/_*'
    - '*.off'
    - 'tryit/**'
    - '**/*.json'
    - 'LICENSE'
    - 'tests/bats/**'
    - 'tests/test_helper/**'
    - '**/*.md'
    - '**/*.txt'
    - '*.code-workspace'
    - 'empty_file'
    - DISCLAIMER
    - LICENSE
    - NOTICE

dependency:
  files:
    - go.mod
  licenses:
    - name: github.com/xi2/xz
      version: v0.0.0-20171230120015-48954b6210f8
      license: Unlicense
    - name: github.com/fatih/color
      version: v1.17.0
      license: MIT
    - name: github.com/go-task/template
      version: v0.0.0-20240602015157-960e6f576656
      license: BSD-3-Clause
    - name: github.com/olekukonko/tablewriter
      version: v0.0.5
      license: MIT
