# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

version: '3'

vars:
    VER:
        sh: git describe --tags --abbrev=0 2>/dev/null || git rev-parse --short HEAD

tasks:
    default: task --list-all

    pre:
      - docker login
 
    validate:
      silent: true
      cmds:
      - echo === "{{.IMG}}"
      - >
        cat validate.sh 
        | docker run -i "{{.IMG}}" 
        env VER="{{.VER}}" EXT="{{.EXT}}" ARCH={{ARCH}} bash -

    ro9:
      - task: validate
        vars:
            EXT: ".rpm"
            IMG: "rockylinux:9"
    
    ubi9:
      - task: validate
        vars:
            EXT: ".rpm"
            IMG: "registry.access.redhat.com/ubi9/ubi:latest"
     
    ostumble:
      - task: validate
        vars:
            EXT: ".rpm"
            IMG: "opensuse/tumbleweed:latest"

    ub22:
      - task: validate
        vars:
            EXT: ".deb"
            IMG: "ubuntu:22.04"

    de12:
      - task: validate
        vars:
            EXT: ".deb"
            IMG: "debian:12"

    ro8:
      - task: validate
        vars:
            EXT: "_redhat8.rpm"
            IMG: "rockylinux:8"

    ubi8:
      - task: validate
        vars:
            EXT: "_redhat8.rpm"
            IMG: "registry.access.redhat.com/ubi8/ubi:latest"
   
    os15:
      - task: validate
        vars:
            EXT: "_redhat8.rpm"
            IMG: "opensuse/leap:latest"
    ub20:
      - task: validate
        vars:
            EXT: "_ubuntu20.deb"
            IMG: "ubuntu:20.04"

    de11:
      - task: validate
        vars:
            EXT: "_ubuntu20.deb"
            IMG: "debian:11"

    osleap:
      - task: validate
        vars:
            EXT: "_redhat8.rpm"
            IMG: "opensuse/leap:latest"


    all:
     - task: pre
     - task: ub22
     - task: ub20
     - task: ubi9
     - task: ubi8
     - task: de12
     - task: de11
     - task: ro9
     - task: ro8
     - task: osleap
     - task: ostumble
